### ISSUE TITLE
GitHub provider doesn’t work with two-factor authentication

### ISSUE THREAD

**Issue by remi** [plehoux/heybill#5]
After entering my GitHub username and password, I get this error:

```
Log in...
Fetch bills...
/Users/remi/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/capybara-2.1.0/lib/capybara/node/finders.rb:41:in `block in find': Unable to find css "#payment-history" (Capybara::ElementNotFound)
…
```

Meanwhile, I’m getting an SMS from GitHub with an authentication code. 

I’m betting the current page seen by PhantomJS is the authentication code form and that’s why it can’t find the invoices.

**Comment by plehoux** [comment]
Interesting challenge, let me work something out!

**Comment by remi** [comment]
Thanks! Just tested it, works great! :grinning:
